spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pc_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    static-path-pattern: /static/**



